// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAniSek7bCfdKPzJ8fVjml-O98C89RtPLo',
    appId: '1:33390656502:web:8cd566ea8e8d9269d765d7',
    messagingSenderId: '33390656502',
    projectId: 'momentum-d7cf3',
    authDomain: 'momentum-d7cf3.firebaseapp.com',
    storageBucket: 'momentum-d7cf3.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBA0Uhvy7pizbph51lYveaXZfYvHMNE2z4',
    appId: '1:33390656502:android:82f0547b2ea1b438d765d7',
    messagingSenderId: '33390656502',
    projectId: 'momentum-d7cf3',
    storageBucket: 'momentum-d7cf3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLl3eWndL-LI0Otks1-0LPQjaEZv2us7E',
    appId: '1:33390656502:ios:94f1ce67c6d95049d765d7',
    messagingSenderId: '33390656502',
    projectId: 'momentum-d7cf3',
    storageBucket: 'momentum-d7cf3.firebasestorage.app',
    iosBundleId: 'com.example.momentum',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCLl3eWndL-LI0Otks1-0LPQjaEZv2us7E',
    appId: '1:33390656502:ios:94f1ce67c6d95049d765d7',
    messagingSenderId: '33390656502',
    projectId: 'momentum-d7cf3',
    storageBucket: 'momentum-d7cf3.firebasestorage.app',
    iosBundleId: 'com.example.momentum',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAniSek7bCfdKPzJ8fVjml-O98C89RtPLo',
    appId: '1:33390656502:web:b4e52e32964d9258d765d7',
    messagingSenderId: '33390656502',
    projectId: 'momentum-d7cf3',
    authDomain: 'momentum-d7cf3.firebaseapp.com',
    storageBucket: 'momentum-d7cf3.firebasestorage.app',
  );
}
